### ISSUE TITLE
Statistics Authority themes

### ISSUE THREAD

**Issue by ajtucker** [ONS-OpenData/ref_common#10]
See GSS-Cogs/GDP-Vocabs#6. We have https://github.com/GSS-Cogs/ref_common/blob/pmd4/reference/codelists/statistics-authority-themes.csv and we previously used `table2qb` to generate concepts under http://gss-data.org.uk.

We now need a `-metadata.json` to put the concepts under `https://osr.statisticsauthority.gov.uk/themes/{theme}/`.

**Comment by rossbowen** [comment]
Started in branch [here](https://github.com/GSS-Cogs/GDP-vocabs/tree/data-taxonomy/vocabs/data-taxonomies/statistics-authority).

Needs to be merged - I didn't look into how Jenkins treats this stuff but someone with knowledge feel free to take what's been done so far and merge into the main branch.

**Comment by ajtucker** [comment]
Merged in. Note that I've used `https://uksa.statisticsauthority.gov.uk/themes/` as the base URI.
