### ISSUE TITLE
ONS Topics

### ISSUE THREAD

**Issue by ajtucker** [ONS-OpenData/ref_common#11]
As per GSS-Cogs/GDP-vocabs#6, ONS topics are listed in the topics pulldown on https://www.ons.gov.uk/timeseriestool.

These appear to be the leaf nodes in the main taxonomy used on the ONS website, and the hierarchical URI path is given for each.

Datasets do not appear to have any topic or taxonomic info in the returned `/data` JSON; @mikeAdamss , could you double check this?

We need to create a simple concept scheme for these leaf node URIs then match the dataset landing page against them in the ONS scraper.

**Comment by mikeAdamss** [comment]
no there's no taxonomy information, or at least not on the ones I checked. The dataset pages _should_ follow the same taxonmy-as-uri pattern as the timeseries' though, all pages on the site have to (its a static file server, all things have to live in a directory, the directories are based on the taxonomy).

**Comment by ajtucker** [comment]
> no there's no taxonomy information, or at least not on the ones I checked. The dataset pages _should_ follow the same taxonmy-as-uri pattern as the timeseries' though, all pages on the site have to (its a static file server, all things have to live in a directory, the directories are based on the taxonomy).

Thanks Mike. I eventually found that you can add `/data` to e.g. `/businessindustryandtrade` and drill down into the taxonomy that way. See https://github.com/GSS-Cogs/ref_common/blob/issue-11/ons-topics/reference/codelists/source/ons-topics.py.

**Comment by ajtucker** [comment]
Ok for now.
